"""Live-Postgres regression test for #113: CHECK constraints honored.

The issue's repro: a Supabase-style `todos` table whose
`task text not null check (char_length(task) between 1 and 200)`
was ignored, so `dataset_strategy(...)` produced `task = ''` and the
INSERT failed with a CheckViolation. Postgres stores that CHECK as
`CHECK (((char_length(task) >= 1) AND (char_length(task) <= 200)))`,
which the old regex refiner could not read.

Covers all three generation routes against a real server:
  * `from_connection_string` (live introspection) + Hypothesis inserts,
  * `from_schema_file` (pglast parse of the source) -> rows Postgres
    accepts,
  * the bulk `load_dataset` COPY path over a table carrying every
    common CHECK shape.
"""

from __future__ import annotations

import os
from pathlib import Path
from uuid import uuid4

import psycopg
import pytest
from hypothesis import HealthCheck, given, settings
from hypothesis import strategies as st

pytestmark = pytest.mark.skipif(
    "SQLPROOF_TEST_DATABASE_URL" not in os.environ,
    reason="set SQLPROOF_TEST_DATABASE_URL to run Postgres integration tests",
)

TODOS_SQL = """
create table {schema}.todos (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  task text not null check (char_length(task) between 1 and 200),
  is_complete boolean not null default false,
  inserted_at timestamptz not null default now()
);
"""

SHAPES_SQL = """
create table {schema}.check_shapes (
  id bigint generated by default as identity primary key,
  task text not null check (char_length(task) between 1 and 200),
  code varchar(12) not null check (length(code) > 2 and length(code) < 6),
  total numeric(10, 2) not null check (total >= 0),
  quantity integer not null check (quantity > 0),
  rating smallint check (rating between 1 and 5),
  ratio double precision not null check (ratio >= 0 and ratio < 1),
  status text not null check (status in ('todo', 'doing', 'done')),
  state varchar(10) not null check (state in ('open', 'closed')),
  name text not null check (name <> ''),
  kind integer not null check (kind not in (0, 1) and kind between 0 and 3),
  age integer check (age >= 18 or age is null)
);
"""


def _create(connection: psycopg.Connection, schema: str, sql: str) -> None:
    connection.execute(sql.format(schema=f'"{schema}"'))


@pytest.fixture
def live_schema():
    dsn = os.environ["SQLPROOF_TEST_DATABASE_URL"]
    schema = f"sqlproof_chk113_{uuid4().hex[:12]}"
    with psycopg.connect(dsn, autocommit=True) as connection:
        connection.execute(f'CREATE SCHEMA "{schema}"')
        try:
            _create(connection, schema, TODOS_SQL)
            _create(connection, schema, SHAPES_SQL)
            yield dsn, schema
        finally:
            connection.execute(f'DROP SCHEMA IF EXISTS "{schema}" CASCADE')


def _auth_users_spec():
    from sqlproof import ExternalTableSpec

    return ExternalTableSpec(
        primary_key="id",
        sample=lambda db: [
            row["id"] for row in db.query("SELECT id::text AS id FROM auth.users LIMIT 5")
        ],
    )


def test_issue_113_todos_from_connection_string_never_violates_task_check(
    live_schema,
) -> None:
    from sqlproof import SqlProof

    dsn, schema = live_schema
    with psycopg.connect(dsn) as connection:
        if connection.execute("SELECT count(*) FROM auth.users").fetchone() == (0,):
            pytest.skip("auth.users has no rows to reference")

    proof = SqlProof.from_connection_string(
        dsn, schema=schema, external_tables={"auth.users": _auth_users_spec()}
    )
    try:
        todos = proof.schema_info.table("todos", schema=schema)
        (check,) = todos.check_constraints
        assert check.parsed is not None, check

        @settings(
            max_examples=25,
            deadline=None,
            suppress_health_check=[HealthCheck.too_slow, HealthCheck.data_too_large],
        )
        @given(data=st.data())
        def run(data: st.DataObject) -> None:
            dataset = data.draw(proof.dataset_strategy(sizes={"todos": 2}))
            for row in dataset["todos"]:
                assert 1 <= len(row["task"]) <= 200, row
            # Inserting is the real oracle: Postgres raises
            # CheckViolation if any generated row breaks the CHECK.
            with proof.client_for_dataset(dataset) as db:
                count = db.scalar(f'SELECT count(*) FROM "{schema}".todos')
                assert count == 2

        run()
    finally:
        proof.disconnect()


def test_issue_113_check_shapes_from_schema_file_are_accepted_by_postgres(
    live_schema, tmp_path: Path
) -> None:
    from sqlproof import SqlProof

    dsn, schema = live_schema
    schema_file = tmp_path / "schema.sql"
    schema_file.write_text(SHAPES_SQL.format(schema="public"))
    proof = SqlProof.from_schema_file(schema_file)
    dataset = proof.dataset_strategy(sizes={"check_shapes": 1})

    rows: list[dict[str, object]] = []

    @settings(max_examples=40, deadline=None, suppress_health_check=[HealthCheck.too_slow])
    @given(data=dataset)
    def collect(data: dict[str, list[dict[str, object]]]) -> None:
        rows.extend(data["check_shapes"])

    collect()
    assert rows
    with psycopg.connect(dsn) as connection:
        for row in rows:
            columns = [c for c in row if c != "id"]
            placeholders = ", ".join(["%s"] * len(columns))
            column_list = ", ".join(columns)
            # Each row in its own savepoint so a failure names the row.
            with connection.transaction():
                connection.execute(
                    f'INSERT INTO "{schema}".check_shapes ({column_list}) VALUES ({placeholders})',
                    [row[c] for c in columns],
                )
        connection.rollback()


def test_issue_113_bulk_load_honors_every_check_shape(live_schema) -> None:
    from sqlproof.scale.load import load_dataset
    from sqlproof.schema.introspect import introspect_schema

    dsn, schema = live_schema
    with psycopg.connect(dsn) as connection:
        with connection.cursor(row_factory=psycopg.rows.dict_row) as cur:
            info = introspect_schema(cur, schema=schema)
        shapes_only = type(info)(
            tables=tuple(t for t in info.tables if t.name == "check_shapes"),
        )
        loaded = load_dataset(connection, shapes_only, {"check_shapes": 2_000}, seed=113)
        assert loaded == {"check_shapes": 2_000}
        connection.rollback()
