"""Edge cases for the SQL schema parser that aren't otherwise covered."""

from __future__ import annotations

import pytest

from sqlproof.exceptions import SqlProofSchemaError
from sqlproof.schema.parse_sql import parse_schema_sql


def test_invalid_sql_raises_sqlproof_schema_error() -> None:
    with pytest.raises(SqlProofSchemaError):
        parse_schema_sql("CREATE TABLE WHATEVER (((")


def test_create_table_only_in_comment_triggers_explicit_error() -> None:
    """When the SQL parses to zero `CreateStmt` statements but the source
    text contains "CREATE TABLE" (e.g. only in a comment), the parser
    raises an explicit "Could not parse" error rather than returning an
    empty SchemaInfo silently."""
    with pytest.raises(SqlProofSchemaError, match="Could not parse"):
        parse_schema_sql("-- CREATE TABLE in a comment\n")


def test_qualified_enum_type_is_resolved_via_unqualified_name() -> None:
    """A column referencing `public.status` should resolve back to the
    declared enum even when the SQL uses the qualified name."""
    sql = """
    CREATE TYPE public.status AS ENUM ('a', 'b');
    CREATE TABLE t (
        id SERIAL PRIMARY KEY,
        s public.status NOT NULL
    );
    """
    info = parse_schema_sql(sql)
    [table] = info.tables
    [_, s_col] = table.columns
    assert s_col.type.kind == "enum"
    assert s_col.type.enum_values == ("a", "b")


def test_identity_always_column_is_recognized() -> None:
    sql = """
    CREATE TABLE t (
        id INTEGER GENERATED ALWAYS AS IDENTITY,
        name TEXT NOT NULL
    );
    """
    info = parse_schema_sql(sql)
    [table] = info.tables
    [id_col, _] = table.columns
    assert id_col.identity == "always"


def test_identity_by_default_column_is_recognized() -> None:
    sql = """
    CREATE TABLE t (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY,
        name TEXT NOT NULL
    );
    """
    info = parse_schema_sql(sql)
    [table] = info.tables
    [id_col, _] = table.columns
    assert id_col.identity == "by_default"


def test_table_level_check_is_captured_alongside_column_level() -> None:
    sql = """
    CREATE TABLE t (
        a INTEGER,
        b INTEGER,
        CHECK (a + b > 0)
    );
    """
    info = parse_schema_sql(sql)
    [table] = info.tables
    assert any("a + b" in chk.expression for chk in table.check_constraints)
